version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mssql
      
  mssql:
    hostname: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pr01nf0@43424140
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
      